- hosts: all
  name: slave playbook
  remote_user: ubuntu
  become: yes

  tasks:

  - name: Upgrade all packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Java OpenJDK 11 
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Install Docker Engine 
    apt:
      name: docker.io
      state: present

  - name: Create the Jenkins folder with appropriate ownership and permissions
    file:
      path: /home/ubuntu/jenkins  # Fixed path
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: "0755"

  - name: Create the Docker group if it doesn't exist
    group:
      name: docker
      state: present

  - name: Add current user to the docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Import HashiCorp GPG key
    shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

  - name: Add HashiCorp APT repository
    shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

  - name: Update apt package cache
    apt:
      update_cache: yes
      
  - name: Install Terraform
    apt:
      name: terraform
      state: present