- hosts: private_ec2
  name: slave playbook
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Upgrade all packages
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Java OpenJDK 11 
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Install Docker Engine 
    apt:
      name: docker.io
      state: present

  - name: Create the Jenkins folder with appropriate ownership and permissions
    file:
      path: /home/ubuntu/jenkins  
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: "0755"

  - name: Create the Docker group if it doesn't exist
    group:
      name: docker
      state: present

  - name: Add current user to the docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
